### ISSUE TITLE
Remove result.model and result-list-model

### ISSUE THREAD

**Issue by mccollum3d** [revaturelabs/cms-frontend#10]
result.model.ts and result-list.model.ts need to be removed, and any content linking to them needs to be refactored.

Result-list.model was used for testing with dummy data. The result.model is a duplicate of the Content model. We don't need 3 models to represent the same object. Any search results returned will be returned as a JSON array of Content.

Content should accept an array of Tag objects, refactor public tags: number[], to tag[], and we can pull the tag names from the nested tag object in the JSON content data returned.

**Comment by PiedPiper11** [comment]
Just searched through front-end files and did not find either of these files. Likely has already been taken care of but I will leave this open for now, just in case.

**Comment by PiedPiper11** [comment]
Closing ticket per Anthony's instruction. Neither of us found these files when we checked this morning
