### ISSUE TITLE
Tag.ts

### ISSUE THREAD

**Issue by mccollum3d** [revaturelabs/cms-frontend#3]
The Tag model does not currently match up with the model object Tag in Java. In order to marshal from JSON, the fields should match. We can create other helper models if we need some additional functionality, but for consistency we should refactor this.

The other models have been updated to use your formatting of declaring the variables within the constructor, it makes the code cleaner to read. Good work.

```js
export class Tag {
  constructor(
    public id: number,
    public name: string,
    public contentId: number,
    public url: string,
    public description: string,
    public category: string
  ) {
  }
}
```

**Comment by PiedPiper11** [comment]
Problem addressed already. Closing ticket
