### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by mccollum3d** [revaturelabs/cms-frontend#4]
Components, Methods, Services, etc... could all use a simple 1-2 line comment explaining what it is, and what it does. Think of the documentation in the java library, what does this do? What values does it accept? If something isn't self-descriptive, it may be worth a brief comment to help future employees work more efficiently on it.

Also, If we have a method stub or placeholder for a future functionality, annotate it.

**Comment by PiedPiper11** [comment]
Updated documentation in tag.ts for variables

**Comment by mccollum3d** [comment]
The team has left comments in the angular project to help explain what variables are and to help annotate the code.
