### ISSUE TITLE
New Searches Append to the List of Results

### ISSUE THREAD

**Issue by Tech314** [revaturelabs/cms-frontend#46]
When searching for content, clicking search appends the new search results to the end of the old search results.

**Comment by mccollum3d** [comment]
Clarification: When searching for more than 1 tag at the same time, the query is returning duplicate results. It returns all content for "where tag=Java" then all content for "JDBC" then all content for "Java AND JDBC"

Search functions as intended for single-tag searches.

**Comment by GibbyH** [comment]
Updated backend ensures only unique results are displayed regardless of how many times a term is searched
