### ISSUE TITLE
Tagging Content when creating content

### ISSUE THREAD

**Issue by mccollum3d** [revaturelabs/cms-frontend#6]
We are currently lacking the back-end functionality to query all tags from the database, but it should be implemented soon. Please complete and test the component to display all valid tags that a user can assign to content, and push the completed "content creation page" to base branch, so we can begin build testing our project as soon as possible.

Thanks.

**Comment by DanG1968** [comment]
Tags service working.  Tags populating from database.  Next hiding duplicates.
