### ISSUE TITLE
Jenkins Pipeline - Front end webhook not triggering

### ISSUE THREAD

**Issue by mccollum3d** [revaturelabs/cms-frontend#7]
Our jenkins configuration for building the front end is missing github credentials, I think this is why the front end has not been getting built but the back end has. Can you please stop by to to check my configuration of the pipeline and fix the issue so the front end begins to build? 

Thanks.

@Quinn-Donnelly

**Comment by PiedPiper11** [comment]
Web hook fixed per Chris. Issue with Tomcat submitted in another ticket
